x-common:
  database:
    &db-environment
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Panel functionality.
    MYSQL_PASSWORD: &db-password "change_me"
    MYSQL_ROOT_PASSWORD: "change_me_root"
  panel:
    &panel-environment
    APP_URL: "http://example.com"
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "UTC"
    APP_SERVICE_AUTHOR: "noreply@example.com"
    # Uncomment the line below and set to a non-empty value if you want to use Let's Encrypt
    # to generate an SSL certificate for the Panel.
    # LE_EMAIL: ""
  mail:
    &mail-environment
    MAIL_FROM: "noreply@example.com"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#
services:
  database:
    image: mariadb:11
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - jexpanel
    volumes:
      - "/srv/jexpanel/database:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "jexpanel_docker"
      MYSQL_USER: "jexpanel_docker"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: redis:alpine
    restart: always
    networks:
      - jexpanel
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  panel:
    image: ghcr.io/jexactyl/jexactyl:latest
    restart: always
    networks:
      - jexpanel
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    volumes:
      - "/srv/jexpanel/var/:/app/var/"
      - "/srv/jexpanel/nginx/:/etc/nginx/http.d/"
      - "/srv/jexpanel/certs/:/etc/letsencrypt/"
      - "/srv/jexpanel/logs/:/app/storage/logs"
      - "./.github/docker/supervisord.conf:/etc/supervisord.conf"
      - "./.github/docker/entrypoint.sh:/entrypoint.sh"
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      DB_USERNAME: "jexpanel_docker"
      DB_DATABASE: "jexpanel_docker"
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      DB_PORT: "3306"
      HASHIDS_LENGTH: 8
networks:
  jexpanel:
    ipam:
      config:
        - subnet: 172.20.0.0/16
