<?php

return [
    // Whether activity logging should be enabled.
    'enabled' => [
        'account' => true, // Account-based activity
        'server' => true, // Server-related tasks
        'admin' => true, // Administrative actions
    ],

    // The number of days elapsed before old activity log entries are deleted.
    'prune_days' => env('APP_ACTIVITY_PRUNE_DAYS', 90),

    // If set to true activity log entries generated by an admin user that is not also
    // a part of the server in question will be hidden from the activity logs API response.
    //
    // Activity will still be properly tracked, just not displayed.
    'hide_admin_activity' => env('APP_ACTIVITY_HIDE_ADMIN', false),
];
